name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: read-all

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3.6.0

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.5

      - name: Set up Node 18.x
        uses: actions/setup-node@v3.8.2
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Check uncommitted formatting changes
        run: pnpm prettier . --check

      - name: Check for linting errors
        run: pnpm lint

      - name: Check shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: >-
            .husky/_
            node_modules

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test -- --ci

  deployment-check:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3.6.0

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.5

      - name: Set up Node 18.x
        uses: actions/setup-node@v3.8.2
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install Node dependencies for deployment
        run: pnpm install --production

      - name: Synthesize CloudFormation template and assets
        run: pnpm synth

      - name: Check synthesized CloudFormation template with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cdk.out
          framework: cloudformation

      - name: Check Github Actions configuration with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .github
          framework: github_actions
