name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.5

      - name: Set up Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Check uncommitted formatting changes
        run: pnpm prettier . --check

      - name: Check for linting errors
        run: pnpm lint

      - name: Check shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: >-
            .husky/_
            node_modules

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test -- --ci

  deployment-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.5

      - name: Set up Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install Node dependencies for deployment
        run: pnpm install --production
        env:
          HUSKY: 0

      - name: Synthesize CloudFormation template and assets
        run: pnpm synth

      - name: Check synthesized CloudFormation template with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cdk.out
          framework: cloudformation

      - name: Check Github Actions configuration with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .github
          framework: github_actions
